export const ENV_VARS = {
    PORT: 'PORT',
    MONGO_DB_USER: 'MONGO_DB_USER',
    MONGO_DB_PASSWORD: 'MONGO_DB_PASSWORD',
    MONGO_DB_URL: 'MONGO_DB_URL',
    MONGO_DB_COLLECTION: 'MONGO_DB_COLLECTION',
}
